before:
  hooks:
    - make crd

builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - linux

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-snapshot"

dockers:
  - image_templates:
      - ghcr.io/containeroo/lieutenant-operator:{{ .Version }}

      # For prereleases, updating `latest` and the floating tags of the major
      # version does not make sense. Only the image for the exact version should
      # be pushed.
      - "{{ if not .Prerelease }}ghcr.io/containeroo/lieutenant-operator:v{{ .Major }}{{ end }}"

      - "{{ if not .Prerelease }}ghcr.io/containeroo/lieutenant-operator:latest{{ end }}"
    use: buildx
    extra_files:
      - LICENSE
release:
  prerelease: auto
  github:
    owner: containeroo
    name: lieutenant-operator
  extra_files:
    - glob: lieutenant-crd.yaml
